// LOCAL
### Get all contacts
GET http://localhost:3000/contacts

### Get contact by id
GET http://localhost:3000/contacts/65e6539e5ad3f6d4d14caf8c

### Get another contact by id
GET http://localhost:3000/contacts/65e6539e5ad3f6d4d14caf8c

// PRODUCTION
### Get all contacts
GET https://cse341-contacts-flu9.onrender.com/contacts

### Get contact by id
GET https://cse341-contacts-flu9.onrender.com/contacts/65e6539e5ad3f6d4d14caf8c

### Get another contact by id
GET https://cse341-contacts-flu9.onrender.com/contacts/65e6539e5ad3f6d4d14caf8c